import { Injectable, signal } from '@angular/core';
import { Offers } from '../models/offers';

@Injectable({
  providedIn: 'root',
})
export class OfferService {
  private offersList = signal<Offers[]>([
    {
      id: 1,
      owner_id: 101,
      title: 'Sahara Palace Douz — Desert Lodge',
      description:
        'A desert lodge at the gateway of the Grand Erg Oriental. Traditional architecture with private hammam, camel paddock, and direct access to the dunes.',
      price: 280,
      discount_percentage: 0,
      date_from: new Date('2025-06-01'),
      date_to: new Date('2025-09-30'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Douz, Kébili',
      rating: 4.7,
      number_of_reviews: 89,
      tag: 'Desert Experience',
      offer_type: 'hotel',
      suffixPrice: '/night',
    },
    {
      id: 2,
      owner_id: 102,
      title: 'La Maison Bleue — Sidi Bou Saïd',
      description:
        'A boutique riad-style hotel in the iconic blue-and-white village, offering panoramic views over the Gulf of Tunis and Andalusian-inspired rooms.',
      price: 320,
      discount_percentage: 10,
      date_from: new Date('2025-05-01'),
      date_to: new Date('2025-10-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Sidi Bou Saïd, Tunis',
      rating: 4.8,
      number_of_reviews: 124,
      tag: 'Boutique Stay',
      offer_type: 'hotel',
      suffixPrice: '/night',
    },
    {
      id: 3,
      owner_id: 103,
      title: 'Médina Dar Zarrouk — Heritage Palace',
      description:
        'A restored 19th-century palace in the heart of Tunis Medina. Steps from the Zitouna Mosque, featuring original tile work and a rooftop restaurant.',
      price: 480,
      discount_percentage: 5,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis Medina, Tunis',
      rating: 4.9,
      number_of_reviews: 201,
      tag: 'Heritage & Culture',
      offer_type: 'hotel',
      suffixPrice: '/night',
    },
    {
      id: 4,
      owner_id: 104,
      title: 'Hôtel Les Orangers — Hammamet',
      description:
        'A classic beachfront hotel surrounded by orange and jasmine gardens in the heart of Hammamet. Direct beach access and a large outdoor pool.',
      price: 195,
      discount_percentage: 15,
      date_from: new Date('2025-06-15'),
      date_to: new Date('2025-08-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Hammamet, Nabeul',
      rating: 4.4,
      number_of_reviews: 310,
      tag: 'Beach & Relaxation',
      offer_type: 'hotel',
      suffixPrice: '/night',
    },
    {
      id: 5,
      owner_id: 105,
      title: 'Sahara Overnight Camel Trek',
      description:
        'A guided 2-day camel trek into the Grand Erg Oriental. Includes a Berber tent overnight stay under the stars, traditional dinner, and sunrise dune walk.',
      price: 350,
      discount_percentage: 0,
      date_from: new Date('2025-10-01'),
      date_to: new Date('2026-03-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Douz, Kébili',
      rating: 4.9,
      number_of_reviews: 178,
      tag: 'Adventure',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
    {
      id: 6,
      owner_id: 106,
      title: 'Carthage & Sidi Bou Saïd Half-Day Tour',
      description:
        "A 4-hour guided walking tour covering the UNESCO ruins of Carthage — Antonine Baths, Tophet, Byrsa Hill — followed by a stroll through Sidi Bou Saïd's iconic streets.",
      price: 95,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Carthage, Tunis',
      rating: 4.7,
      number_of_reviews: 312,
      tag: 'History & Culture',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
    {
      id: 7,
      owner_id: 105,
      title: 'Medina Artisan Workshop Walk',
      description:
        'A 3-hour immersive tour through the souks of Tunis Medina. Visits to active craft workshops — weaving, copperwork, pottery — and a guided tasting at a spice merchant.',
      price: 75,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis Medina, Tunis',
      rating: 4.8,
      number_of_reviews: 97,
      tag: 'Craft & Heritage',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
    {
      id: 8,
      owner_id: 104,
      title: 'El Jem Amphitheatre Guided Tour',
      description:
        'A 3-hour expert-guided tour of the Roman Colosseum of El Jem, one of the best-preserved Roman amphitheatres in the world. Includes underground gallery access and museum entry.',
      price: 85,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'El Jem, Mahdia',
      rating: 4.8,
      number_of_reviews: 254,
      tag: 'Roman History',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
    {
      id: 9,
      owner_id: 102,
      title: 'Djerba Quad & Dunes Adventure',
      description:
        'A 2-hour guided quad bike tour across the sandy tracks and coastal dunes of Djerba. Suitable for beginners. Helmet, gloves, and brief training included.',
      price: 120,
      discount_percentage: 10,
      date_from: new Date('2025-04-01'),
      date_to: new Date('2025-10-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Djerba, Médenine',
      rating: 4.5,
      number_of_reviews: 143,
      tag: 'Adventure & Thrills',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
    {
      id: 10,
      owner_id: 103,
      title: 'Au Bon Vieux Temps — Traditional Tunisian',
      description:
        "A legendary family restaurant inside the Tunis Medina serving recipes passed down three generations. Famous for brick à l'oeuf, lamb couscous, and homemade makroudh.",
      price: 45,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis Medina, Tunis',
      rating: 4.8,
      number_of_reviews: 430,
      tag: 'Traditional Cuisine',
      offer_type: 'restaurant',
    },
    {
      id: 11,
      owner_id: 102,
      title: 'Dar Zarrouk Rooftop — Fine Dining',
      description:
        'Modern Tunisian cuisine with 360° panoramic views of the Medina skyline and Gulf of Tunis. Seasonal tasting menus and a curated selection of Tunisian wines. Ideal for sunset dinners.',
      price: 130,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis Medina, Tunis',
      rating: 4.7,
      number_of_reviews: 186,
      tag: 'Fine Dining',
      offer_type: 'restaurant',
    },
    {
      id: 12,
      owner_id: 106,
      title: 'La Tente Berbère — Desert Dining',
      description:
        'Authentic Berber tent restaurant at the edge of the Douz dunes. Slow-cooked mechoui, kemia platters, and a Saharan tea ceremony under the stars with traditional Bedouin music.',
      price: 65,
      discount_percentage: 0,
      date_from: new Date('2025-10-01'),
      date_to: new Date('2026-04-30'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Douz, Kébili',
      rating: 4.6,
      number_of_reviews: 95,
      tag: 'Unique Experience',
      offer_type: 'restaurant',
    },
    {
      id: 13,
      owner_id: 106,
      title: 'Le Baroque — Sidi Bou Saïd Terrace',
      description:
        'A charming café-restaurant overlooking the Gulf of Tunis. Famous for its almond croissants, Tunisian shakshuka, and fresh seafood platters. Perfect for a long leisurely lunch.',
      price: 55,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Sidi Bou Saïd, Tunis',
      rating: 4.5,
      number_of_reviews: 287,
      tag: 'Sea View',
      offer_type: 'restaurant',
    },
    {
      id: 14,
      owner_id: 104,
      title: 'Essaray El Morjane — Djerba Seafood',
      description:
        'A waterfront seafood restaurant in Houmt Souk, Djerba. Known for grilled sea bass, octopus salad, and a wide selection of fresh catches bought daily from local fishermen.',
      price: 70,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Houmt Souk, Djerba',
      rating: 4.6,
      number_of_reviews: 192,
      tag: 'Fresh Seafood',
      offer_type: 'restaurant',
    },
    {
      id: 15,
      owner_id: 101,
      title: 'Tunis–Douz Private Transfer',
      description:
        'Door-to-door private air-conditioned transfer from any Tunis address to Douz. Comfortable 7-seat minivan with professional driver. One-way or round-trip available. All luggage included.',
      price: 380,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis → Douz',
      rating: 4.7,
      number_of_reviews: 64,
      tag: 'Private Transfer',
      offer_type: 'transportation',
    },
    {
      id: 16,
      owner_id: 105,
      title: 'Tunis–Carthage Airport Transfer',
      description:
        'Professional meet-and-greet airport pickup with name sign at arrivals. Available 24/7 including late-night flights. Flight tracking included. Sedan or minivan depending on group size.',
      price: 55,
      discount_percentage: 0,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis–Carthage International Airport',
      rating: 4.8,
      number_of_reviews: 342,
      tag: 'Airport Transfer',
      offer_type: 'transportation',
    },
    {
      id: 17,
      owner_id: 104,
      title: 'Tunis–Carthage–Sidi Bou Saïd Day Shuttle',
      description:
        'Scheduled shared shuttle departing daily from Place de Barcelone at 9:00 AM. Stops at Carthage ruins and Sidi Bou Saïd, returning to Tunis by 5:00 PM. Ideal for day-trippers.',
      price: 35,
      discount_percentage: 0,
      date_from: new Date('2025-04-01'),
      date_to: new Date('2025-10-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis → Carthage → Sidi Bou Saïd',
      rating: 4.5,
      number_of_reviews: 218,
      tag: 'Shared Shuttle',
      offer_type: 'transportation',
    },
    {
      id: 18,
      owner_id: 103,
      title: 'Tunis–Djerba Private Minivan',
      description:
        'Comfortable private transfer from Tunis to Djerba island via the Djorf–Ajim ferry crossing. 7-seat air-conditioned minivan with an experienced driver. Scenic coastal route.',
      price: 490,
      discount_percentage: 5,
      date_from: new Date('2025-01-01'),
      date_to: new Date('2025-12-31'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tunis → Djerba',
      rating: 4.6,
      number_of_reviews: 47,
      tag: 'Private Transfer',
      offer_type: 'transportation',
    },
    {
      id: 19,
      owner_id: 101,
      title: 'Hammamet–Tunis Express Shuttle',
      description:
        'Daily air-conditioned shared minibus service between Hammamet city center and central Tunis. Departs at 8:00 AM and 3:00 PM. Return trip included. Ideal for day visitors.',
      price: 28,
      discount_percentage: 0,
      date_from: new Date('2025-06-01'),
      date_to: new Date('2025-09-30'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Hammamet → Tunis',
      rating: 4.3,
      number_of_reviews: 133,
      tag: 'Shared Shuttle',
      offer_type: 'transportation',
    },
    {
      id: 20,
      owner_id: 106,
      title: 'Tabarka Snorkeling & Coral Reef Tour',
      description:
        'A 3-hour guided snorkeling excursion in the protected marine reserve of Tabarka, home to rare red coral formations. Equipment, wetsuit, and an underwater guide included. Max 8 participants.',
      price: 110,
      discount_percentage: 0,
      date_from: new Date('2025-06-01'),
      date_to: new Date('2025-09-30'),
      image_url: ['images/sahara-tunisia.jpg'],
      location: 'Tabarka, Jendouba',
      rating: 4.9,
      number_of_reviews: 61,
      tag: 'Marine & Nature',
      offer_type: 'activity',
      suffixPrice: '/person',
    },
  ]);

  getOffers() {
    return this.offersList();
  }

  getOfferById(id: number): Offers | undefined {
    return this.offersList().find((offer) => offer.id === id);
  }
}
